baseurl = "http://journeytowardpeace.com.s3-website.us-east-2.amazonaws.com/"
languageCode = "en-us"
pluralizelisttitles = "false"
title = "Journey Toward Peace"
copyright = "© Journey Toward Peace {year}"
